server:
  port: 8080

spring:
  application:
    name: sbliquibase
  main:
    lazy-initialization: true
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/sbliquibase
    username: sbliquibase
    password: sbliquibase
    driver-class-name: org.postgresql.Driver
    tomcat:
      connection-properties: stringtype=unspecified
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 3000
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

logging:
  config: "classpath:log4j2-dev.xml"
